bbs/urls.py
from django.conf.urls import url

from . import views

app_name = 'bbs'

urlpatterns = [
    url(r'^topic/(?P<pk>[0-9]+)/$', views.TopicView.as_view(), name='topic-view'),
    url(r'^topic/(?P<topic_id>[0-9]+)/reply/$', views.PostCreate.as_view(), name='post-create'),
    url(r'^topic/create/$', views.TopicCreate.as_view(), name='topic-create'),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.PostUpdate.as_view(), name='post-edit'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^$', views.CategoryView.as_view(), name='categories'),
]

bbs/templates/bbs/list_topics.html
{% extends "allianceauth/base.html" %}
{% load static %}
{% load i18n %}

{% block page_title %}
    {% if category %}
        {% blocktrans %}Viewing {{ category }} Topics{% endblocktrans %}
    {% else %}
        {% trans "Viewing All Topics" %}
    {% endif %}
{% endblock page_title %}

{% block content %}
    <div class="col-lg-12 col-md-12">
        <h2 class="page-header">
            {% if category %}
                {% blocktrans %}Viewing {{ category }} Topics{% endblocktrans %}
            {% else %}
                {% trans "Viewing All Topics" %}
            {% endif %}
        </h2>
        <div class="list-group">
            <div class="list-group-item active">
                <a href="{% url 'bbs:topic-create' %}" class="btn btn-sm btn-default">New Topic</a>
            </div>
            {% if topics %}
                {% for topic in topics %}
                <a class="list-group-item {% if topic.pinned %}active{% endif %}"
                   style="min-height: 60px;" href="{% url 'bbs:topic-view' pk=topic.pk %}">
                    <div class="col-md-4 col-sm-9 col-xs-10">
                        <div class="pull-left avatar" style="padding-right:8px;">
                            <img src="https://imageserver.eveonline.com/Character/{{ topic.created_by.profile.main_character.character_id }}_32.jpg"
                                 alt="{{ topic.created_by.profile.main_character.character_name }}"
                                 title="{{ topic.created_by.profile.main_character.character_name }}"
                                 class="img-circle"/>
                        </div>
                        <b>
                            {{ topic.title }}
                        </b>
                        <br>
                        <small class="hidden-xs">
                            {% blocktrans with character_name=topic.created_by.profile.main_character.character_name created=topic.created_date|timesince %}
                                {{ created }} ago by {{ character_name }}
                            {% endblocktrans %}
                        </small>
                    </div>
                    <div class="col-md-4 hidden-sm hidden-xs text-right">
                        <div style="line-height: 0.5em;">&nbsp;</div> {% comment %} My filthy dirty v-align hack :( {% endcomment %}
                        {{ topic.category }}
                    </div>
                    <div class="col-md-1 hidden-sm hidden-xs text-center">
                        <small>
                            <b>
                                {{ topic.views }}
                                <br>
                                {% trans "Views" %}
                            </b>
                        </small>
                    </div>
                    <div class="col-md-1 hidden-sm hidden-xs text-center">
                        <small>
                            <b>
                                {{ topic.posts.all|length }}
                                <br>
                                {% trans "Posts" %}
                            </b>
                        </small>
                    </div>
                    <div class="col-md-2 hidden-sm hidden-xs">
                        <small>
                            <b>
                                {% if topic.posts.all %}
                                    {% with last_post=topic.posts.all.last %}
                                        {% blocktrans with character_name=last_post.created_by.profile.main_character %}
                                            Last Reply By {{ character_name }}
                                        {% endblocktrans %}
                                        <br>
                                        {% blocktrans with created=last_post.created_date|timesince %}
                                            {{ created }} ago
                                        {% endblocktrans %}
                                    {% endwith %}
                                {% else %}
                                    No Replies
                                {% endif %}
                            </b>
                        </small>
                    </div>
                </a>
                {% endfor %}
            {% else %}
            <div class="list-group-item">
                <strong>No Topics Found</strong>
            </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

bbs/templates/bbs/post_form.html
{% load static %}
{% load bootstrap %}
{% load i18n %}

<div class="col-lg-12">
    <h3 class="page-header">{% trans "Reply" %}</h3>
    <form role="form" method="post" action="{% url 'bbs:post-create' topic_id=topic_id %}">
        {% csrf_token %}
        {{ form.id }}
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            {{ form.content }}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

bbs/templates/bbs/topic_form.html
{% extends "allianceauth/base.html" %}
{% load static %}
{% load bootstrap %}
{% load i18n %}

{% block page_title %}{% trans "Create Topic" %}{% endblock page_title %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header">{% trans "Create Topic" %}</h1>
        <form role="form" method="post" action="">
            {% csrf_token %}
            {{ form.id }}
            <div class="col-lg-4 col-md-5 col-sm-12 col-xs-12">
                {{ form.title|bootstrap }}
                {{ form.category|bootstrap }}
            </div>
            <div class="clearfix"></div>
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                {{ form.content|bootstrap }}
            </div>
            <div class="clearfix"></div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

{% block extra_javascript %}
    {{ form.media }}
{% endblock extra_javascript %}

bbs/templates/bbs/view_topic.html
{% extends "allianceauth/base.html" %}
{% load static %}
{% load bootstrap %}
{% load martortags %}
{% load i18n %}
{% load l10n %}
{% load tz %}

{% block page_title %}{{ topic.title }}{% endblock page_title %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header">{% blocktrans with topic_title=topic.title %}Topic: {{ topic_title }}{% endblocktrans %}</h1>
        {% for post in topic.posts.all %}
            <div class="panel {% if forloop.first %}panel-primary{% else %}panel-default{% endif %}">
                <div class="panel-heading">
                    <img src="https://imageserver.eveonline.com/Character/{{ post.created_by.profile.main_character.character_id }}_32.jpg"
                         alt="{{ post.created_by.profile.main_character.character_name }}"
                         title="{{ post.created_by.profile.main_character.character_name }}"
                         class="img-circle"/>
                    {{ post.created_by.profile.main_character.character_name }}
                    &#8226;
                    {{ post.created_date|localtime|localize }}
                </div>
                <div class="panel-body">
                    {{ post.content|safe_markdown }}
                </div>
            </div>
        {% endfor %}
        {% include 'bbs/post_form.html' with topic_id=topic.pk %}
    </div>
{% endblock content %}

{% block extra_javascript %}
    {{ form.media }}
{% endblock extra_javascript %}